version: '3.8'
services:
  webapp:
    image: multiinstancewebapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 3
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - webapp